### ISSUE TITLE
start -h, --height overlaps with start -h, --help

### ISSUE THREAD

**Issue by jaredpetersen** [jaredpetersen/raspi-live#13]
Running `raspi-live start -h` tries to start livestreaming with a height option rather than outputting start help.

The short name for the `height` option needs to change. Not sure what it should be though, since it's only allowed to be one character.

**Comment by jontsai** [comment]
Yeah, I think you'd have to re-map the options, or get rid of the short options for some.

`fswebcam` does `-r` for resolution which takes a combination of height and width, and `--fps` for frame rate.

**Comment by jaredpetersen** [comment]
I think you're right; I'm going to have to re-map the options which unfortunately means a major revision. Sigh...

`-r` is already taken by `--framerate` (r for f**R**amerate since `-f` was already taken by `--format`). I like the `-r 1280x720` idea though.

I'll probably just switch to not using CLI shortcut names at all. It's difficult to get one character shortcuts that are meaningful to the operation they perform.
