### ISSUE TITLE
took over my desktop

### ISSUE THREAD

**Issue by figuerres** [jaredpetersen/raspi-live#27]
after i installed the software and ran the rasp-live start command 
a video stream from my camera took over the screen and i could not get back to a terminal window to stop it.

not sure if this is a known issue or a bug or some thinbg else.

had to pull the power on the pi to reboot it,

checking for l,ogs and info now.

**Comment by figuerres** [comment]
running the command with stdout and stderr piped to log files allowed me to use control c to stop it.
i also can say that i had full video on my local screen.
when i tried to access the pi over the network from chrome it tried to play but just spun.... not sure what the problem is.
i did see that the stdout logging showed no errors and did show the code running.
stderr log was empty.

also the /home/user/camera folder is created and was beeing written to but linux tools installed do not play the files -- not sure what to do at this point.

**Comment by figuerres** [comment]
the pull request seems to be the same thing i have seen, i have an hdmi screen connected while i try to create the video server.   this is hapening and does take over the desktop.
https://github.com/jaredpetersen/raspi-live/pull/23

**Comment by jaredpetersen** [comment]
Hi @figuerres,

I normally use this software on a headless Raspberry Pi so I don't run into this problem. It sounds like a `-n` placed at the end of the array [here](https://github.com/jaredpetersen/raspi-live/blob/master/lib/server.js#L16) and a version revision to 2.0.2 is all that's needed.

I would merge #23 but it makes two unnecessary changes that the author has neglected to resolve. If you submit a new pull request that adds that flag I'd happily accept it.

**Comment by figuerres** [comment]
i am investigating this issue and i am starting to think that something about ffmpeg on the pi is in error and that this might be an issue to resolve with the ffmpeg developers.

the -n  or --nopreview are not in the ffmpeg info i have found so far....  i can't find this option.
also i ran a different command and had the same problem and was not able to make a -n do anything.

so if i find out what is up i will post here with any news.

i also saw another command that might get me what i need so if this ffmpeg is not a simple fix and the other way does what i want i may just go with something that works ....

right now i think your code is ok, i think this is an ffmpeg issue , perhaps even a new issue as i pulled the source and built it on my pi, so might be a new bug.

**Comment by jaredpetersen** [comment]
Oh, interesting. My initial thought is that it's `raspivid`'s fault. `raspivid` is the utility responsible for capturing video from the Raspberry Pi Camera Module and it has a bunch of pre-processing video options.

Here's the doc for `raspivid`: https://www.raspberrypi.org/app/uploads/2013/07/RaspiCam-Documentation.pdf

There's a section in there on the option `-n, --no-preview`:

> Do not display a preview window
> Disables the preview window completely. Note that even though
the preview is disabled, the camera will still be producing frames,
so will be using power.

This seems like a reasonable culprit. I don't think Ffmpeg has anything to do with opening display windows -- it's just a video processing tool.

**Comment by figuerres** [comment]
i think you are right, i am new at these camera and video utilities on linux and i did not see in your code that you call raspvid .... so i was only looking at ffmpeg options !

**Comment by jaredpetersen** [comment]
This should be fixed now 😄
