### ISSUE TITLE
Run at boot

### ISSUE THREAD

**Issue by smoki3** [jaredpetersen/raspi-live#33]
Is it possible to start the service at boot?

**Comment by jaredpetersen** [comment]
Yes, this is something that is handled by a utility like systemd.

Here's some information about it:
- https://learn.sparkfun.com/tutorials/how-to-run-a-raspberry-pi-program-on-startup/all (Method 3)
- https://wiki.debian.org/systemd/Services
- https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units
