### ISSUE TITLE
question - how can I set brightness and saturation parameters?

### ISSUE THREAD

**Issue by beejones** [jaredpetersen/raspi-live#41]
Hi,

Thanks for your code. I really hope to use it on my installation.

Is there a way to set additional parameters such as brightness and saturation?

Suggestion, it would be nice to configure a default webpage showing your stream.

Thanks

**Comment by jaredpetersen** [comment]
`raspivid` supports those options with [`--brightness` and `--saturation`](https://www.raspberrypi.org/documentation/raspbian/applications/camera.md).

We don't have a way to pass those parameters in at this time, so you'd have to add those options [here](https://github.com/jaredpetersen/raspi-live/blob/1e2ba1086494d406d5121f3b756c836afd996d97/lib/server.js#L33).

**Comment by beejones** [comment]
Thanks. It would be great to have the possibility to pass in a dictionary with key/values in order to set one or more of these zillion of settings.
Regards
