### ISSUE TITLE
ffmpeg fails to compile on newest version of raspbian

### ISSUE THREAD

**Issue by ZaneL** [jaredpetersen/raspi-live#43]
In the readme this line:
`sudo ./configure --arch=arm --target-os=linux --enable-gpl --enable-omx --enable-omx-rpi --enable-nonfree
`

Needs an extra flag at the end:
`sudo ./configure --arch=arm --target-os=linux --enable-gpl --enable-omx --enable-omx-rpi --enable-nonfree --extra-ldflags="-latomic"`

or else the compilation throws this `error: undefined reference to__atomic_store_8`

**Comment by ZaneL** [comment]
Also thanks so much for putting this library together. This thing is sweet!

I'm streaming high quality video from my pi camera to my PC and it's only using 5-10% of my PI3B+'s CPU. So cool!

**Comment by jaredpetersen** [comment]
Cool, thanks for letting me know! Would you be willing to put up a pull request? Otherwise, I'll get to it as soon as I can.

Glad you enjoy it!

**Comment by jaredpetersen** [comment]
Thanks for putting in #44!
