### ISSUE TITLE
Instructions need a little update to force link atomic lib.

### ISSUE THREAD

**Issue by fusionstream** [jaredpetersen/raspi-live#45]
Note that in the latest version of raspberry os (formerly raspbian), you need to add:
```./configure --extra-ldflags="-latomic" ...```

Otherwise you'll wait forever for it to compile only to find it failed.

Details available here:
https://stackoverflow.com/questions/62374298/ffmpeg-installation-on-raspberry-pi-zero-w-undefined-references-to-atomic

**Comment by jaredpetersen** [comment]
I believe the README has already been updated to address this:

> 1. Download and configure FFmpeg via:
> ```
> sudo apt-get install libomxil-bellagio-dev
> wget -O ffmpeg.tar.bz2 https://ffmpeg.org/releases/ffmpeg-snapshot-git.tar.bz2
> tar xvjf ffmpeg.tar.bz2
> cd ffmpeg
> sudo ./configure --arch=arm --target-os=linux --enable-gpl --enable-omx --enable-omx-rpi --enable-nonfree --extra-ldflags="-latomic"
> ```

https://github.com/jaredpetersen/raspi-live#ffmpeg

**Comment by fusionstream** [comment]
Ah. Right at the end. Apologies for missing that. In that case could I draw your attention to updating it on the website as well. I put a comment there already. Cheers.
