### ISSUE TITLE
Returns 404

### ISSUE THREAD

**Issue by ahoffer** [jaredpetersen/raspi-live#46]
I installed raspi-live on a Raspberry Pi 2B+ with a version 1 camera.
I ran raspi-live as a normal user `raspi-live start`
I entered the URL `http://webcam.local:8080` into Chrome browser.

I expected a video to start playing.
The raspi-live server instead gave me a 404: `GET http://webcam.local:8080/ 404 (Not Found)`

The raspi-live executable printed:

```
configuration: /home/pi/camera hls 1280 720 25 false false 9 2 10 10 8080 false  
camera stream server started
```

and it continuously printed the FFMPEG log.

The .m4s files, an init.mp4 file and the .m3u8 file are all in the expected location of `/home/pi/camera`, where `pi` is the user.

I do not know how to debug it further.

**Comment by jaredpetersen** [comment]
I'm not sure where you got `http://webcam.local:8080`.

The server runs on localhost so the base url should be `localhost:8080` on the Raspberry Pi. The full path to the livestream manifest will be `localhost:8080/camera/livestream.m3u8` for HLS (default) or `localhost:8080/camera/livestream.mpd` for DASH.
