### ISSUE TITLE
How many parallel connections it can handle?

### ISSUE THREAD

**Issue by dmfilipenko** [jaredpetersen/raspi-live#57]
Did you measure, how many connections it could handle on average, with a basic raspberry pi?

**Comment by jaredpetersen** [comment]
Nope!

**Comment by jaredpetersen** [comment]
Closing out since I don't have the resources to investigate this. If others would like to take this on and document their findings, great!

This was always built with personal use in mind rather than starting a DIY home security empire. So a "couple" of connections was fine for my use.
